name: 'gz_dbt_repository'
version: '1.0.0'

profile: 'gz_dbt_repository'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gz_dbt_repository:
    circle_parcel:
      +schema: parcel_dbt_dev
      staging:
        +schema: parcel_dbt_dev_staging